version: 2.0

jobs:
  "Test":
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - pip install pipenv
      - pipenv install
      - bundle update
      - bundle exec fastlane test
      - bundle exec rubocop
      - bundle exec danger || echo "danger failed, moving on"
  "Deploy":
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - pip install pipenv
      - pipenv install
      - ./scripts/ci/deploy.sh
    branches:
      only:
        - master  

workflows:
  version: 2
  build:
    jobs:
      - "Test"
      - "Deploy"
