version: 2.0

jobs:
  "Test Docs":
    docker:
      - image: joshdholtz/fastlane-docs:0.0.1
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    working_directory: ~/code
    steps:
      - checkout
      - run: pip3 install pipenv
      - run: pipenv install
      - run: bundle update
      - run: pipenv run bundle exec fastlane test
      - run: bundle exec rubocop
      - run: bundle exec danger || echo "danger failed, moving on"
  "Deploy Docs":
    docker:
      - image: joshdholtz/fastlane-docs:0.0.1
    steps:
      - run: pip3 install pipenv
      - run: pipenv install
      - run: pipenv run ./scripts/ci/deploy.sh
    branches:
      only:
        - master  

workflows:
  version: 2
  build:
    jobs:
      - "Test Docs"
      - "Deploy Docs"
