version: 2.0

jobs:
  "Test":
    docker: # Replace this with a fastlane owned docker image at some point
      - image: joshdholtz/fastlane-docs:0.0.1
    working_directory: ~/code
    steps:
      - checkout
      - run: pip3 install pipenv
      - run: pipenv install
      - run: bundle update
      - run: pipenv run bundle exec fastlane test
      - run: bundle exec rubocop
      - run: bundle exec danger || echo "danger failed, moving on"
  "Deploy":
    docker:
      - image: joshdholtz/fastlane-docs:0.0.1
    working_directory: ~/code
    steps:
      - checkout
      - run: pip3 install pipenv
      - run: pipenv install
      - run: pipenv run ./scripts/ci/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - "Test"
      - "Deploy":
          filters:
            branches:
              only: master-test
