version: 2.0

jobs:
  "Test":
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - run: sudo apt-get install python3-pip
      - run: pip3 install pipenv
      - run: pipenv install
      - run: bundle update
      - run: bundle exec fastlane test
      - run: bundle exec rubocop
      - run: bundle exec danger || echo "danger failed, moving on"
  "Deploy":
    docker:
      - image: circleci/ruby:2.3-jessie
    steps:
      - run: sudo apt-get install python3-pip
      - run: pip3 install pipenv
      - run: pipenv install
      - run: ./scripts/ci/deploy.sh
    branches:
      only:
        - master  

workflows:
  version: 2
  build:
    jobs:
      - "Test"
